# Generated by Django 4.1.5 on 2023-01-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sorc', models.CharField(choices=[('г', 'Город'), ('г.о.', 'Городской округ'), ('гп', 'Городской поселок'), ('д', 'Деревня'), ('с', 'Село')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('octd', models.CharField(max_length=100, null=True)),
                ('gnimb', models.CharField(max_length=100, null=True)),
                ('uno', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SorcName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('sorc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sorc', models.CharField(choices=[('гфз', 'Город федерального значения'), ('Аобл', 'Автономная область'), ('Аобл', 'Автономный округ'), ('край', 'Край'), ('обл', 'Область'), ('округ', 'Округ'), ('Респ', 'Республика')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('octd', models.CharField(max_length=100, null=True)),
                ('gnimb', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sorc', models.CharField(choices=[('пер', 'Переулок'), ('ул', 'Улица'), ('а/я', 'Абонентский ящик'), ('аллея', 'Аллея'), ('мкр', 'Микрорайон'), ('проезд', 'Проезд')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('octd', models.CharField(max_length=100)),
                ('gnimb', models.CharField(max_length=100, null=True)),
                ('index', models.CharField(max_length=100, null=True)),
                ('citygpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.citygpt')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sorc', models.CharField(choices=[('ДОМ', 'Дом')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('octd', models.CharField(max_length=100, null=True)),
                ('gnimb', models.CharField(max_length=100, null=True)),
                ('index', models.CharField(max_length=100, null=True)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.street')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField()),
                ('floor', models.SmallIntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.house')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sorc', models.CharField(choices=[('р-н', 'Район')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('octd', models.CharField(max_length=100, null=True)),
                ('gnimb', models.CharField(max_length=100, null=True)),
                ('uno', models.CharField(max_length=100, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.subject')),
            ],
        ),
        migrations.AddField(
            model_name='citygpt',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fias.district'),
        ),
    ]
